/// Generated by AssetsRefGenerator on 2022/01/05
class Res {
  static const String imageone = "assets/Images/imageone.png";
  static const String loginbac = "assets/Images/loginbac.png";
  static const String passwordicon = "assets/Images/passwordicon.png";
  static const String profileavatar = "assets/Images/profileavatar.png";
  static const String profilebac = "assets/Images/profilebac.png";
  static const String profileicon = "assets/Images/profileicon.png";
  static const String splashbac = "assets/Images/splashbac.png";
}
